modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://github.com/williambl/the-hateful-sun/issues/"

[[mods]]
modId="thehatefulsun"
version="${file.jarVersion}"
displayName="The Hateful Sun"
updateJSONURL="https://github.com/williambl/the-hateful-sun/blob/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-hateful-sun"
logoFile="logo.png"
credits=""
authors="Willbl3pic"
description='''
When it's the day of a new moon, the sun will mutate living beings!
'''
[[dependencies.thehatefulsun]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.thehatefulsun]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
